Run collectstatic as Job during deploy

diff --git a/.circleci/deploy_to_kubernetes b/.circleci/deploy_to_kubernetes
--- a/.circleci/deploy_to_kubernetes
+++ b/.circleci/deploy_to_kubernetes
@@ -1,4 +1,5 @@
 #!/bin/bash -e
+set -o pipefail
 
 ROOT=$(dirname "$0")
 NAMESPACE="$1"
@@ -22,6 +23,31 @@ fi
 
 echo "Deploying $ECR_DEPLOY_IMAGE to $NAMESPACE..."
 
+echo "Running jobs"
+COLLECT_STATIC=$NAMESPACE_DIR/collect-static-job.yml
+
+for JOB in $COLLECT_STATIC
+do
+  echo "Running $JOB"
+  kubectl delete -f $JOB --ignore-not-found
+  cat $JOB| \
+    kubectl set image app="$ECR_DEPLOY_IMAGE" --filename=/dev/stdin --local --output=yaml | \
+    kubectl annotate kubernetes.io/change-cause="$CIRCLE_BUILD_URL" --filename=/dev/stdin --local --output=yaml | \
+    kubectl apply --record=false --filename=/dev/stdin
+done
+
+echo "Waiting for jobs"
+if ! kubectl wait --for=condition=complete -f $COLLECT_STATIC --timeout=180s ; then
+  echo "Failed pods:"
+  kubectl get pods --field-selector=status.phase=Failed
+  FIRST_POD=$(kubectl get pods --field-selector=status.phase=Failed -o=name | head -n 1)
+  echo "
+Logs for failed pod $FIRST_POD:"
+    kubectl logs $FIRST_POD
+  exit 1
+fi
+
+echo "Deploying app"
 kubectl set image --filename="$NAMESPACE_DIR/deployment.yml" --local --output=yaml \
   app="$ECR_DEPLOY_IMAGE" | \
   kubectl apply \
